# Create a new video blog
POST http://localhost:3000/api/blog HTTP/1.1
Content-Type: application/json

{
  "type": "video",
  "content": {
    "name": "Cute cats",
    "link": "https://www.youtube.com/watch?v=y0sF5xhGreA"
  },
  "author": "Adam Smash",
  "tags": ["thebest"]
}

###

# Create a new text blog
POST http://localhost:3000/api/blog HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "content": {
    "name": "Cute cats",
    "annotation": "cats",
    "content": "cute cats play together"
  },
  "author": "Adam Morgan",
  "tags": ["cats"]
}

###

# Login user by email and password
GET http://localhost:3000/api/blog/915ec3db-4a98-455d-aad0-0e911b86ed6c HTTP/1.1
Content-Type: application/json

###

# Change user password
PUT http://localhost:3000/api/blog/7123d427-3dab-4938-979f-fa836157434f HTTP/1.1
Content-Type: application/json

{
  "postedDate": "2023-12-12",
  "status": "public",
  "content": {
    "name": "Cute cats - 2",
    "link": "https://www.youtube.com/watch?v=z3U0udLH974"
  },
  "tags": ["thebest", "fanny"]
}

###

# Change user password
DELETE http://localhost:3000/api/blog/7123d427-3dab-4938-979f-fa836157434f HTTP/1.1
Content-Type: application/json

###
