# Create a new user
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.locale",
  "name": "Ivan Ivanovich",
  "password": "123456"
}

###

# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Change user password
PUT http://localhost:3001/api/auth/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgxZDNlMTgyNDYwMTViZjlhZWI1M2QiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiSXZhbiBJdmFub3ZpY2giLCJpYXQiOjE3MDYwMTU1NDksImV4cCI6MTcwNjAxOTE0OX0.jL17O8UcL328p4knAK1b8dSQSWX2ERXGGj-CzuaOOGs

{
  "id": "6581d3e18246015bf9aeb53d",
  "oldPassword": "123456",
  "newPassword": "123456"
}

###


# refresh user token
POST http://localhost:3001/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTgxZDNlMTgyNDYwMTViZjlhZWI1M2QiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiSXZhbiBJdmFub3ZpY2giLCJ0b2tlbklkIjoiNjg5YmVmYjgtNzJhYy00YTE4LWFiNjgtMzliZWNmN2M0MjYwIiwiaWF0IjoxNzA1OTE3MTg2LCJleHAiOjE3MDYwMDM1ODZ9.OKWxMdIoDMnp7pueyVI_un7NfFlq3SIwYLFeeuln2yE

###

# Check user token
POST http://localhost:3001/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQwMzJmYmU0Y2FlYjg2OGM2ZWVjMzYiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjgzMTIxMzU1LCJleHAiOjE2ODMxMjE5NTV9.laK4-SAzu_ZMznRVsRWrHxELTGu_P48kpY_CwHPjxtk

###
